# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28fb04eb9d0fff0ad7f5e84d7723875ba8e1e66d87386e9f017ca34394b5990ac39f0f056984401b5b09e826b5461c10d84564149cdb140d9e785669b7dbfa50

test:
  secret_key_base: b6e59cda3eab40d8e601b9ffbc8e189f005eead756f8f1d58818e4c47841c1cf5bc0e790155a82436222caedde5684bc94c64c43eea9f671b4ec80a19d5fc3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
